'use strict';
module.exports = (sequelize, DataTypes) => {
  const Like = sequelize.define('Like', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    }
    // createdAt and updatedAt are auto-generated by sequelize.
  });
  Like.associate = function (models) {
    Like.belongsTo(models.User, {
      foreignKey: {
        allowNull: false
      },
    })
    Like.belongsTo(models.Post, {
      foreignKey: {
        allowNull: false
      }
    })
  };
  return Like;
};