'use strict';
module.exports = (sequelize, DataTypes) => {
  const Post = sequelize.define('Post', {
    content: {
      type: DataTypes.TEXT,
      allowNull: false,
      validate: {
        is: emojiRegex
      }
    },
    postID: {
      type: DataTypes.INTEGER,
      autoIncrement: true
    },
    replyTo: {
      type: sequelize.INTEGER,
    }
    // createdAt and updatedAt are auto-generated by sequelize.
  },{
    instanceMethods: {
      getReplyingTo: function() {
        return this.sequelize.models.Post.findByPrimary(this.replyID)
      },
      setReplyingTo: function(ReplyingToPost){
        return this.update({ replyID: replyingToPost.id })
    }
  }
  });
  Post.associate = function (models) {
    Post.belongsTo(models.User, {
      foreignKey: {
        allowNull: false
      }
    })
    Post.hasMany(models.Post, {
      as: 'Replies',
      foreignKey: 'replyID'
    })
  }
return Post;
};