const Op = require('sequelize').Op;
module.exports = function (sequelize, DataTypes) {
    const Token = sequelize.define('Token', {
        id: {
            allowNull: false,
            primaryKey: true,
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4
        }
        // createdAt and updatedAt are auto-generated by sequelize.  
    });

    Token.associate = function (models) {
        Token.belongsTo(models.User, {
            foreignKey: {
                userId: models.User.id
            }
        });
    };

    Token.deleteExpiredForUser = async function (userId) {
        const twentyMinutesAgo = new Date().setMinutes(new Date().getMinutes() - 20)
        await Token.destroy({
            where: {
                UserId: userId,
                [Op.and]: {
                    updatedAt: {
                        [Op.lt]: twentyMinutesAgo
                    }
                }
            }
        });
    };

    Token.deleteExpiredForAll = function() {
        Token.destroy({
            where: {
                updatedAt: {
                    [Op.lt]: new Date().getTime() - 1200000000
                }
            }
        })
    }

    return Token;
};